### ISSUE TITLE
issues with Java unmarshalling at channel level

### ISSUE THREAD

**Issue by rtweekly-earthscope** [iris-edu/irisFetch-matlab#17]
Some calls to the irisFetch.Traces method as well as channel- and response-level calls using irisFetch.Stations method are causing the following errors:

```
>> mysta = irisFetch.Stations('channel','GM','NMP31','*','HH?')
Sep 07, 2022 3:58:40 PM com.sun.xml.internal.bind.v2.util.XmlFactory createTransformerFactory
SEVERE: null
javax.xml.transform.TransformerConfigurationException: Unsupported feature: http://javax.xml.XMLConstants/feature/secure-processing
	at com.icl.saxon.TransformerFactoryImpl.setFeature(TransformerFactoryImpl.java:373)
	at com.sun.xml.internal.bind.v2.util.XmlFactory.createTransformerFactory(XmlFactory.java:169)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.createTransformerHandler(JAXBContextImpl.java:712)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.DomLoader$State.<init>(DomLoader.java:60)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.DomLoader.startElement(DomLoader.java:103)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.ProxyLoader.startElement(ProxyLoader.java:45)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:60)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXEventConnector.handleStartElement(StAXEventConnector.java:246)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXEventConnector.bridge(StAXEventConnector.java:115)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:445)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:415)
	at edu.iris.dmc.service.station.parser.StationXMLParser.parse(StationXMLParser.java:252)
	at edu.iris.dmc.service.StationService.fetch(StationService.java:407)
	at edu.iris.dmc.service.StationService.fetch(StationService.java:316)
	at edu.iris.dmc.service.StationService.fetch(StationService.java:338)

Error using irisFetch/Networks/fetchTheStations (line 809)
Java exception occurred:
java.lang.IllegalStateException: javax.xml.transform.TransformerConfigurationException: Unsupported
feature: http://javax.xml.XMLConstants/feature/secure-processing
	at com.sun.xml.internal.bind.v2.util.XmlFactory.createTransformerFactory(XmlFactory.java:173)
	at
    com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.createTransformerHandler(JAXBContextImpl.java:712)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.DomLoader$State.<init>(DomLoader.java:60)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.DomLoader.startElement(DomLoader.java:103)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.ProxyLoader.startElement(ProxyLoader.java:45)
	at
    com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
    	at
    com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
    	at
    com.sun.xml.internal.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:60)
    	at
    com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXEventConnector.handleStartElement(StAXEventConnector.java:246)
    	at
    com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXEventConnector.bridge(StAXEventConnector.java:115)
    	at
    com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:445)
    	at
    com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:415)
	at edu.iris.dmc.service.station.parser.StationXMLParser.parse(StationXMLParser.java:252)
	at edu.iris.dmc.service.StationService.fetch(StationService.java:407)
	at edu.iris.dmc.service.StationService.fetch(StationService.java:316)
	at edu.iris.dmc.service.StationService.fetch(StationService.java:338)
Caused by: javax.xml.transform.TransformerConfigurationException: Unsupported feature:
http://javax.xml.XMLConstants/feature/secure-processing
	at com.icl.saxon.TransformerFactoryImpl.setFeature(TransformerFactoryImpl.java:373)
	at com.sun.xml.internal.bind.v2.util.XmlFactory.createTransformerFactory(XmlFactory.java:169)
	... 15 more

Error in irisFetch.Networks (line 713)
         fetchTheStations();

Error in irisFetch.Stations (line 639)
         [stationStructure, urlParams] = irisFetch.Networks(detailLevel,varargin{:});
 
```

This error does not appear to be a global issue that affects all requests, as these requests appear to work fine:

```
>> mysta = irisFetch.Stations('station','OO','AXAS1','*','EHN','startTime','2022-01-01 00:00:00','2022-01-02 00:00:00')
>> mysta = irisFetch.Stations('channel','OO','AXAS1','*','EHN','startTime','2022-01-01 00:00:00','2022-01-02 00:00:00')
>> tr = irisFetch.Traces('OO','AXAS1','*','EHN','2020-01-01 00:00:00','2020-01-02 00:00:00','verbose')
```

Matlab version: 2021b
IRIS-WS version: 2.0.19

**Comment by rtweekly-earthscope** [comment]
Other problematic requests:
```
>> tr = irisFetch.Traces('CI','PASC','00','BHZ','2015-01-01 00:00:00','2015-01-01 00:10:00')  
    <-- note the bracketed comment "[LOGGER::Q330HR::1839]" from 2015-06-24T00:00:00.0000; <Site>::<Description> present, with punctuation

>> tr = irisFetch.Traces('GM','S1AL','00','HH1','2019-04-01 00:00:00','2019-04-01 00:01:00')  
    <-- brackets in comments; hashtag in <Site>::<Name>; <Site>::<Description> attribute present

>> tr = irisFetch.Traces('C0','CHIL','*','HHE','2021-01-01 00:00:00','2021-01-01 00:10:00','verbose')
    <-- brackets in comments; No <Site>::<Description>, but does have <Site>::<Town> and <Site>::<Region>
```

**Comment by rtweekly-earthscope** [comment]
One that doesn't work, and one that does...

```
>> mysta = irisFetch.Stations('channel','_GSN','*','*','BHZ','starttime','2022-07-26 00:00:00','endtime','2022-07-28 00:00:00')
    <-- broken

>> mysta = irisFetch.Stations('channel','_GSN','-PASC','*','BHZ','starttime','2022-07-26 00:00:00','endtime','2022-07-28 00:00:00')
    <-- success
```

**Comment by rtweekly-earthscope** [comment]
Notable difference in StationXML between service versions.

New sub-elements in `<Site>` element. Used to only be `<Name>`, but now also have `<Description>`,` <Town>`,` <Region>`, and `<Country>`.

Element `<Equipment>` has been changed to `<Datalogger>` for some stations, notably for all problem use cases listed above.

**Comment by rtweekly-earthscope** [comment]
Determined to be an issue with the generation of StationXML. In this case, the `<Datalogger>` element had a case sensitivity problem and should have instead been generated as `<DataLogger>` . After fixing this in the station service and deploying, we did not continue to see any issues with using irisFetch.m .
