### ISSUE TITLE
Requesting null instrument response

### ISSUE THREAD

**Issue by rtweekly-iris** [iris-edu/irisFetch-matlab#3]
There are some channels that have timeseries data but do not include instrument response information. An example is the hydrophone data associated with the Ocean Observatories network (**net=OO**). When these "null" response channels are requested while using the **includePZ** option, the Traces method will crash and not return any timeseries data. This is due to how the IRIS-WS library interacts with the irisws-sacpz service to get response information.

The result is that the exception below will crash and not return any data at all. Ideally, what ought to happen is for the library to skip past that channel's empty response information and continue to serve the timeseries data as well as the response information, when applicable.

```
trace = irisFetch.Traces('OO','AXCC1','*','HHZ,HDH',736696,736696+1/24/60,'includePZ','verbose');

An [MATLAB:Java:GenericException] exception occurred in irisFetch.getTheTraces() but was caught full text follows:
message:
Java exception occurred: 
edu.iris.dmc.service.DataFormatException: Unable to parse data: Constant not found where expected
    at edu.iris.dmc.service.SacpzService.fetch(SacpzService.java:432)
    at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:465)
    at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:203)
    at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:144)
    at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:108)
```

**Comment by rtweekly-iris** [comment]
This has been addressed by ver 2.0.17 of IRIS-WS java library
