### ISSUE TITLE
no data incorrectly returned with federated requests that use 'includePZ' flag

### ISSUE THREAD

**Issue by rtweekly-iris** [iris-edu/irisFetch-matlab#6]
Federated requests go to multiple datacenters, which may not host a version of the sacpz web service. When irisFetch.Traces method invokes the 'includePZ' option, this can result in a "no data" error despite the datacenter having the timeseries and associated metadata available.

This behavior is not exclusive to federated requests and will occur if the sacpz web service is generally unreachable.

An example:
```
tr = irisFetch.Traces('II,GR','BFO,XBFO','*','LHZ','2019-08-17 00:00:00','2019-08-18 00:00:00','includePZ','federated','verbose')
Fetching data from BGR (http://eida.bgr.de)
[BGR] : DATACENTER > http://eida.bgr.de
[BGR] : DATASELECTSERVICE > http://eida.bgr.de/fdsnws/dataselect/1/
[BGR] : STATIONSERVICE > http://eida.bgr.de/fdsnws/station/1/
query : net=II,GR&sta=BFO,XBFO&loc=*&cha=LHZ&start=2019-08-17T00:00:00.000&end=2019-08-18T00:00:00.000
traces = tracedata.fetchTraces("GR", "BFO", "--", "LHZ", "2019-08-17 00:00:00.000", "2019-08-18 00:00:00.000", 'M', 1)
2019/09/09 10:33:20 INFO: edu.iris.dmc.extensions.fetch.TraceData fetchTraces: StationService url set to: http://eida.bgr.de/fdsnws/station/1/
2019/09/09 10:33:21 FINER: edu.iris.dmc.extensions.fetch.TraceData usrMessage: Found  1 applicable metadata
2019/09/09 10:33:21 INFO: edu.iris.dmc.extensions.fetch.TraceData fetchTraces: WaveService url set to: http://eida.bgr.de/fdsnws/dataselect/1/
2019/09/09 10:33:21 FINER: edu.iris.dmc.extensions.fetch.TraceData usrMessage: Requesting: GR BFO -- LHZ 2019-08-17T00:00:00.000 2019-08-18T00:00:00.000
2019/09/09 10:33:21 FINER: edu.iris.dmc.extensions.fetch.TraceData usrMessage: Fetching waveform data
2019/09/09 10:33:22 INFO: edu.iris.dmc.extensions.fetch.TraceData fetchTraces: SacpzService url set to: http://service.iris.edu/irisws/sacpz/1/
2019/09/09 10:33:22 FINER: edu.iris.dmc.extensions.fetch.TraceData usrMessage: Matching waveform to metadata: 
	GR,BFO,,LHZ,48.33007,8.329563,589.0,0.0,0.0,-90.0,null,2.5169897E9,1.0,m/s,1.0,2011-10-19T00:00:00

An [MATLAB:Java:GenericException] exception occurred in irisFetch.getTheTraces() but was caught
 full text follows:
message:
Java exception occurred: 
java.io.IOException
	at edu.iris.dmc.service.SacpzService.fetch(SacpzService.java:463)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:464)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:202)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:143)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:107)

Received 0 channels in 1.4 seconds

```

**Comment by xtyangpsp** [comment]
I had the same error. Is this being taken care of?

**Comment by rtweekly-iris** [comment]
Yes the plan is to address this in the next update of irisFetch.m, however, there will still be no way to retrieve SACPZ formatted metadata from Federated requests to FDSN datacenters that do not provide support for a sacpz web service. Instead, the request will gracefully exit with whatever metadata it can scrape from datacenters that do offer such a service.

**Comment by rtweekly-iris** [comment]
This issue is fixed with the most recent releases of irisFetch.m and the accompanying IRIS-WS Java library, found here: http://ds.iris.edu/ds/nodes/dmc/software/downloads/IRIS-WS/2-0-19/#Download
