### ISSUE TITLE
problems with specifying other FDSN event services

### ISSUE THREAD

**Issue by rtweekly-iris** [iris-edu/irisFetch-matlab#8]
A couple problems when trying to specify non-IRIS fdsnws-event service URLs

- The IRIS-WS library wants to append the below parameters to every request. In the v 1.1 version of the FDSN spec, support for these parameters is considered optional. This is especially problematic for IRIS PH5 services.
  - includearrivals=false
  - includeallmagnitudes=false
  - includeallorigins=false

- The following error occurs when trying to send requests to the USGS event web service (https://earthquake.usgs.gov/fdsnws/event/1/). Potentially related to https vs http ?

> Oct 15, 2019 10:10:10 PM com.sun.xml.internal.bind.v2.util.XmlFactory createTransformerFactory
> SEVERE: null
> javax.xml.transform.TransformerConfigurationException: Unsupported feature: http://javax.xml.XMLConstants/feature/secure-processing
> 	at com.icl.saxon.TransformerFactoryImpl.setFeature(TransformerFactoryImpl.java:373)
> 	at com.sun.xml.internal.bind.v2.util.XmlFactory.createTransformerFactory(XmlFactory.java:169)
> 	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.createTransformerHandler(JAXBContextImpl.java:712)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.DomLoader$State.<init>(DomLoader.java:60)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.DomLoader.startElement(DomLoader.java:103)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.ProxyLoader.startElement(ProxyLoader.java:45)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:60)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXEventConnector.handleStartElement(StAXEventConnector.java:246)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXEventConnector.bridge(StAXEventConnector.java:115)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:445)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:415)
> 	at edu.iris.dmc.service.EventService.fetch(EventService.java:182)
> 	at edu.iris.dmc.service.EventService.fetch(EventService.java:113)
> 
> Error using irisFetch.Events (line 983)
> Java exception occurred:
> java.lang.IllegalStateException: javax.xml.transform.TransformerConfigurationException:
> Unsupported feature: http://javax.xml.XMLConstants/feature/secure-processing
> 	at
>         com.sun.xml.internal.bind.v2.util.XmlFactory.createTransformerFactory(XmlFactory.java:173)
>         	at
>         com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.createTransformerHandler(JAXBContextImpl.java:712)
>         	at
>         com.sun.xml.internal.bind.v2.runtime.unmarshaller.DomLoader$State.<init>(DomLoader.java:60)
>         	at
>         com.sun.xml.internal.bind.v2.runtime.unmarshaller.DomLoader.startElement(DomLoader.java:103)
>         	at
>         com.sun.xml.internal.bind.v2.runtime.unmarshaller.ProxyLoader.startElement(ProxyLoader.java:45)
>         	at
>         com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
>         	at
>         com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
>         	at
>         com.sun.xml.internal.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:60)
>         	at
>         com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXEventConnector.handleStartElement(StAXEventConnector.java:246)
>         	at
>         com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXEventConnector.bridge(StAXEventConnector.java:115)
>         	at
>         com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:445)
>         	at
>         com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:415)
>         	at edu.iris.dmc.service.EventService.fetch(EventService.java:182)
> 	at edu.iris.dmc.service.EventService.fetch(EventService.java:113)
> Caused by: javax.xml.transform.TransformerConfigurationException: Unsupported feature:
> http://javax.xml.XMLConstants/feature/secure-processing
> 	at com.icl.saxon.TransformerFactoryImpl.setFeature(TransformerFactoryImpl.java:373)
> 	at
>         com.sun.xml.internal.bind.v2.util.XmlFactory.createTransformerFactory(XmlFactory.java:169)
>         	... 13 more

**Comment by rtweekly-iris** [comment]
Will be opening a new issue on this topic.
