### ISSUE TITLE
'inlcudePZ' no longer working

### ISSUE THREAD

**Issue by jbrussell** [iris-edu/irisFetch-matlab#9]
Adding the 'includePZ' flag now causes a java error and is unable to retrieve traces or the poles and zeros

As an example
```mytrace=irisFetch.Traces('IU','ANMO','00','BHZ','2010-02-27 06:30:00','2010-02-27 07:30:00','includePZ')```
Produces the error:
> java.text.ParseException: Unparseable date: ""
	at java.text.DateFormat.parse(DateFormat.java:357)
	at edu.iris.dmc.service.SacpzService.fetch(SacpzService.java:195)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:464)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:202)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:143)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:107)

and ```mytrace``` is an empty 1x0 structure

Any help would be much appreciated!

**Comment by jbrussell** [comment]
Not sure if this helps, but seems to fail at line 475-476 of irisFetch:

``` traces = tracedata.fetchTraces(N, S, L, C, ...
                     startDateStr, endDateStr, opts.quality, opts.getsacpz, opts.username, opts.userpwd);```

>java.text.ParseException: Unparseable date: ""
	at java.text.DateFormat.parse(DateFormat.java:357)
	at edu.iris.dmc.service.SacpzService.fetch(SacpzService.java:195)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:464)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:202)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:143)
Java exception occurred:
java.lang.Exception: Problem interpreting SacPZ metedata for
this time segment; multiple entries found!:
[net=IU&sta=ANMO&cha=BHZ&loc=00&starttime=2010-02-27T06:30:00&endtime=2010-02-27T07:29:59]
	at
edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:467)
	at
edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:202)
	at
edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:143)

**Comment by danauerbach** [comment]
Hitting this as well with v2.0.18.

Digging into the code a bit, the problem appears to stem from the **SacpzService** failing to parse empty/blank END dates in current/open epochs (see line 195 in SacpzService.java). 

Note that the problem exists even when requesting a trace from an epoch prior to the current epoch because the service at http://service.iris.edu/irisws/sacpz/1/  returns the SACPZ responses for all epochs, including the current/open epoch with blank END date.

**Comment by jbrussell** [comment]
Just to update, I sent an email to the folks at the IRIS DMC. They are aware of the issue and working on it:

Feb 10, 2020, 11:23 AM
>>> This is a known issue that occurred following our station service upgrade last week.  The nature of the error has to do with new business rules we introduced to our metadata output, specifically our omission of end times when a channel is currently active.  Our testing of internal tools did not catch this issue in time for the library that irisFetch uses, so we're working to resolve this as soon as possible.  You'll find that data access without the SACPZ inclusion should still work in the meantime.
>>>
>>>	I'm sorry for the inconvenience this has caused and we'll work quickly to get you back in operation with an update to irisFetch.m
>>>
>>>	-Rob

My current workaround is to pull instrument response using irisFetch.Resp. I've written a script to extract the poles, zeros, and sensitivity from the RESP structure and attach them to the trace.
https://github.com/jbrussell/recreadplot/blob/master/matguts/read_sac_resp.m

**Comment by danauerbach** [comment]
This issue appears to have been resolved by the recent rollback of the **irisws-sacpz** web service.
